require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BaristaController do

  def mock_baristum(stubs={})
    @mock_baristum ||= mock_model(Baristum, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all barista as @barista" do
      Baristum.stub(:all) { [mock_baristum] }
      get :index
      assigns(:barista).should eq([mock_baristum])
    end
  end

  describe "GET show" do
    it "assigns the requested baristum as @baristum" do
      Baristum.stub(:find).with("37") { mock_baristum }
      get :show, :id => "37"
      assigns(:baristum).should be(mock_baristum)
    end
  end

  describe "GET new" do
    it "assigns a new baristum as @baristum" do
      Baristum.stub(:new) { mock_baristum }
      get :new
      assigns(:baristum).should be(mock_baristum)
    end
  end

  describe "GET edit" do
    it "assigns the requested baristum as @baristum" do
      Baristum.stub(:find).with("37") { mock_baristum }
      get :edit, :id => "37"
      assigns(:baristum).should be(mock_baristum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created baristum as @baristum" do
        Baristum.stub(:new).with({'these' => 'params'}) { mock_baristum(:save => true) }
        post :create, :baristum => {'these' => 'params'}
        assigns(:baristum).should be(mock_baristum)
      end

      it "redirects to the created baristum" do
        Baristum.stub(:new) { mock_baristum(:save => true) }
        post :create, :baristum => {}
        response.should redirect_to(baristum_url(mock_baristum))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved baristum as @baristum" do
        Baristum.stub(:new).with({'these' => 'params'}) { mock_baristum(:save => false) }
        post :create, :baristum => {'these' => 'params'}
        assigns(:baristum).should be(mock_baristum)
      end

      it "re-renders the 'new' template" do
        Baristum.stub(:new) { mock_baristum(:save => false) }
        post :create, :baristum => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested baristum" do
        Baristum.stub(:find).with("37") { mock_baristum }
        mock_baristum.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :baristum => {'these' => 'params'}
      end

      it "assigns the requested baristum as @baristum" do
        Baristum.stub(:find) { mock_baristum(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:baristum).should be(mock_baristum)
      end

      it "redirects to the baristum" do
        Baristum.stub(:find) { mock_baristum(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(baristum_url(mock_baristum))
      end
    end

    describe "with invalid params" do
      it "assigns the baristum as @baristum" do
        Baristum.stub(:find) { mock_baristum(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:baristum).should be(mock_baristum)
      end

      it "re-renders the 'edit' template" do
        Baristum.stub(:find) { mock_baristum(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested baristum" do
      Baristum.stub(:find).with("37") { mock_baristum }
      mock_baristum.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the barista list" do
      Baristum.stub(:find) { mock_baristum }
      delete :destroy, :id => "1"
      response.should redirect_to(barista_url)
    end
  end

end
