require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FavoriteShopsController do

  def mock_favorite_shop(stubs={})
    @mock_favorite_shop ||= mock_model(FavoriteShop, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all favorite_shops as @favorite_shops" do
      FavoriteShop.stub(:all) { [mock_favorite_shop] }
      get :index
      assigns(:favorite_shops).should eq([mock_favorite_shop])
    end
  end

  describe "GET show" do
    it "assigns the requested favorite_shop as @favorite_shop" do
      FavoriteShop.stub(:find).with("37") { mock_favorite_shop }
      get :show, :id => "37"
      assigns(:favorite_shop).should be(mock_favorite_shop)
    end
  end

  describe "GET new" do
    it "assigns a new favorite_shop as @favorite_shop" do
      FavoriteShop.stub(:new) { mock_favorite_shop }
      get :new
      assigns(:favorite_shop).should be(mock_favorite_shop)
    end
  end

  describe "GET edit" do
    it "assigns the requested favorite_shop as @favorite_shop" do
      FavoriteShop.stub(:find).with("37") { mock_favorite_shop }
      get :edit, :id => "37"
      assigns(:favorite_shop).should be(mock_favorite_shop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created favorite_shop as @favorite_shop" do
        FavoriteShop.stub(:new).with({'these' => 'params'}) { mock_favorite_shop(:save => true) }
        post :create, :favorite_shop => {'these' => 'params'}
        assigns(:favorite_shop).should be(mock_favorite_shop)
      end

      it "redirects to the created favorite_shop" do
        FavoriteShop.stub(:new) { mock_favorite_shop(:save => true) }
        post :create, :favorite_shop => {}
        response.should redirect_to(favorite_shop_url(mock_favorite_shop))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved favorite_shop as @favorite_shop" do
        FavoriteShop.stub(:new).with({'these' => 'params'}) { mock_favorite_shop(:save => false) }
        post :create, :favorite_shop => {'these' => 'params'}
        assigns(:favorite_shop).should be(mock_favorite_shop)
      end

      it "re-renders the 'new' template" do
        FavoriteShop.stub(:new) { mock_favorite_shop(:save => false) }
        post :create, :favorite_shop => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested favorite_shop" do
        FavoriteShop.stub(:find).with("37") { mock_favorite_shop }
        mock_favorite_shop.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :favorite_shop => {'these' => 'params'}
      end

      it "assigns the requested favorite_shop as @favorite_shop" do
        FavoriteShop.stub(:find) { mock_favorite_shop(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:favorite_shop).should be(mock_favorite_shop)
      end

      it "redirects to the favorite_shop" do
        FavoriteShop.stub(:find) { mock_favorite_shop(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(favorite_shop_url(mock_favorite_shop))
      end
    end

    describe "with invalid params" do
      it "assigns the favorite_shop as @favorite_shop" do
        FavoriteShop.stub(:find) { mock_favorite_shop(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:favorite_shop).should be(mock_favorite_shop)
      end

      it "re-renders the 'edit' template" do
        FavoriteShop.stub(:find) { mock_favorite_shop(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested favorite_shop" do
      FavoriteShop.stub(:find).with("37") { mock_favorite_shop }
      mock_favorite_shop.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the favorite_shops list" do
      FavoriteShop.stub(:find) { mock_favorite_shop }
      delete :destroy, :id => "1"
      response.should redirect_to(favorite_shops_url)
    end
  end

end
