require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ShopCheckinsController do

  def mock_shop_checkin(stubs={})
    @mock_shop_checkin ||= mock_model(ShopCheckin, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all shop_checkins as @shop_checkins" do
      ShopCheckin.stub(:all) { [mock_shop_checkin] }
      get :index
      assigns(:shop_checkins).should eq([mock_shop_checkin])
    end
  end

  describe "GET show" do
    it "assigns the requested shop_checkin as @shop_checkin" do
      ShopCheckin.stub(:find).with("37") { mock_shop_checkin }
      get :show, :id => "37"
      assigns(:shop_checkin).should be(mock_shop_checkin)
    end
  end

  describe "GET new" do
    it "assigns a new shop_checkin as @shop_checkin" do
      ShopCheckin.stub(:new) { mock_shop_checkin }
      get :new
      assigns(:shop_checkin).should be(mock_shop_checkin)
    end
  end

  describe "GET edit" do
    it "assigns the requested shop_checkin as @shop_checkin" do
      ShopCheckin.stub(:find).with("37") { mock_shop_checkin }
      get :edit, :id => "37"
      assigns(:shop_checkin).should be(mock_shop_checkin)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created shop_checkin as @shop_checkin" do
        ShopCheckin.stub(:new).with({'these' => 'params'}) { mock_shop_checkin(:save => true) }
        post :create, :shop_checkin => {'these' => 'params'}
        assigns(:shop_checkin).should be(mock_shop_checkin)
      end

      it "redirects to the created shop_checkin" do
        ShopCheckin.stub(:new) { mock_shop_checkin(:save => true) }
        post :create, :shop_checkin => {}
        response.should redirect_to(shop_checkin_url(mock_shop_checkin))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved shop_checkin as @shop_checkin" do
        ShopCheckin.stub(:new).with({'these' => 'params'}) { mock_shop_checkin(:save => false) }
        post :create, :shop_checkin => {'these' => 'params'}
        assigns(:shop_checkin).should be(mock_shop_checkin)
      end

      it "re-renders the 'new' template" do
        ShopCheckin.stub(:new) { mock_shop_checkin(:save => false) }
        post :create, :shop_checkin => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested shop_checkin" do
        ShopCheckin.stub(:find).with("37") { mock_shop_checkin }
        mock_shop_checkin.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :shop_checkin => {'these' => 'params'}
      end

      it "assigns the requested shop_checkin as @shop_checkin" do
        ShopCheckin.stub(:find) { mock_shop_checkin(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:shop_checkin).should be(mock_shop_checkin)
      end

      it "redirects to the shop_checkin" do
        ShopCheckin.stub(:find) { mock_shop_checkin(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(shop_checkin_url(mock_shop_checkin))
      end
    end

    describe "with invalid params" do
      it "assigns the shop_checkin as @shop_checkin" do
        ShopCheckin.stub(:find) { mock_shop_checkin(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:shop_checkin).should be(mock_shop_checkin)
      end

      it "re-renders the 'edit' template" do
        ShopCheckin.stub(:find) { mock_shop_checkin(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested shop_checkin" do
      ShopCheckin.stub(:find).with("37") { mock_shop_checkin }
      mock_shop_checkin.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the shop_checkins list" do
      ShopCheckin.stub(:find) { mock_shop_checkin }
      delete :destroy, :id => "1"
      response.should redirect_to(shop_checkins_url)
    end
  end

end
