require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserLocationsController do

  def mock_user_location(stubs={})
    @mock_user_location ||= mock_model(UserLocation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all user_locations as @user_locations" do
      UserLocation.stub(:all) { [mock_user_location] }
      get :index
      assigns(:user_locations).should eq([mock_user_location])
    end
  end

  describe "GET show" do
    it "assigns the requested user_location as @user_location" do
      UserLocation.stub(:find).with("37") { mock_user_location }
      get :show, :id => "37"
      assigns(:user_location).should be(mock_user_location)
    end
  end

  describe "GET new" do
    it "assigns a new user_location as @user_location" do
      UserLocation.stub(:new) { mock_user_location }
      get :new
      assigns(:user_location).should be(mock_user_location)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_location as @user_location" do
      UserLocation.stub(:find).with("37") { mock_user_location }
      get :edit, :id => "37"
      assigns(:user_location).should be(mock_user_location)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user_location as @user_location" do
        UserLocation.stub(:new).with({'these' => 'params'}) { mock_user_location(:save => true) }
        post :create, :user_location => {'these' => 'params'}
        assigns(:user_location).should be(mock_user_location)
      end

      it "redirects to the created user_location" do
        UserLocation.stub(:new) { mock_user_location(:save => true) }
        post :create, :user_location => {}
        response.should redirect_to(user_location_url(mock_user_location))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_location as @user_location" do
        UserLocation.stub(:new).with({'these' => 'params'}) { mock_user_location(:save => false) }
        post :create, :user_location => {'these' => 'params'}
        assigns(:user_location).should be(mock_user_location)
      end

      it "re-renders the 'new' template" do
        UserLocation.stub(:new) { mock_user_location(:save => false) }
        post :create, :user_location => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_location" do
        UserLocation.stub(:find).with("37") { mock_user_location }
        mock_user_location.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :user_location => {'these' => 'params'}
      end

      it "assigns the requested user_location as @user_location" do
        UserLocation.stub(:find) { mock_user_location(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:user_location).should be(mock_user_location)
      end

      it "redirects to the user_location" do
        UserLocation.stub(:find) { mock_user_location(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(user_location_url(mock_user_location))
      end
    end

    describe "with invalid params" do
      it "assigns the user_location as @user_location" do
        UserLocation.stub(:find) { mock_user_location(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:user_location).should be(mock_user_location)
      end

      it "re-renders the 'edit' template" do
        UserLocation.stub(:find) { mock_user_location(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_location" do
      UserLocation.stub(:find).with("37") { mock_user_location }
      mock_user_location.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the user_locations list" do
      UserLocation.stub(:find) { mock_user_location }
      delete :destroy, :id => "1"
      response.should redirect_to(user_locations_url)
    end
  end

end
